name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Android Project
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK (Android Studio uses Java 17 for latest Gradle)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Give execution permission to gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      # 5. Run unit tests
      - name: Run tests
        run: ./gradlew test
